### ISSUE TITLE
Symfony is not required

### ISSUE THREAD

**Issue by garak** [UPDG/roadrunner-symfony#1]

**Comment by Alex-Bond** [comment]
Hi @garak!

What do you mean? We not requiring Symfony because we want maximum versions coverage.

**Comment by garak** [comment]
That's not fair: you should require anything needed to run your code.
If you want maximum version coverage, declare all vendor version you want to support (that is also fair because explicit)

**Comment by Alex-Bond** [comment]
@garak let me consult with some devs. I will come back to you.

**Comment by Alex-Bond** [comment]
@garak sorry for the long answer. I just added deps to the repo.
Thank you for the issue report.
