### ISSUE TITLE
min php version

### ISSUE THREAD

**Issue by Gemorroj** [UPDG/roadrunner-symfony#5]
https://github.com/UPDG/roadrunner-symfony/blob/master/composer.json#L12-L13
says it supports symfony `2.8`
symfony 2.8 support php 5.3 (https://github.com/symfony/symfony/blob/2.8/composer.json#L19)
but code use syntax php >= 7.
![Захват-1](https://user-images.githubusercontent.com/885731/63086030-a1419300-bf57-11e9-8407-a4a2cb48eacf.png)

**Comment by alexeyshockov** [comment]
One can easily run Symfony 2.8 on PHP 7.3, so I don't see any conflicts here. Symfony 2.8 has PHP 5.3 as the minimum, not maximum.

In the end it just means that the combination of this package and Sf 2.8 can be used only on PHP 7+.

**Comment by Gemorroj** [comment]
if you do not want to upgrade the symfony version, you must specify the minimum php version. because it is now 5.3 (from symfony).

**Comment by alexeyshockov** [comment]
I don't really see any issues running Symfony 2.8 with this package on PHP 7.2 (for example)...

BTW, I just realized that the package is not available on Packagist O_o. @Alex-Bond, is it a mistake, or is it intentional?..

**Comment by Alex-Bond** [comment]
@alexeyshockov oops. fixed.

**Comment by Gemorroj** [comment]
@alexeyshockov problem with php < 7. Not 7+.
Should be say minimum php version in composer. https://github.com/symfony/symfony/blob/2.8/composer.json#L19

**Comment by alexeyshockov** [comment]
OK, I still don't see any issues here (the package don't have to support all the PHP versions that Symfony 2.8 supports).

But I'm not the maintainer, nor I have this issue :) Was just walking around and decided to add my 5 cents. So letting it to the maintainer.

**Comment by Gemorroj** [comment]
> the package don't have to support all the PHP versions

But which versions of php are supported? I don't have to learn the syntax of the code and guess it. Currently, the minimum version of php is inherited from symfony and is 5.3.9. You should specify the real minimum version of php in composer.

**Comment by Alex-Bond** [comment]
I pushed an update and create version 0.0.1. Please, check if its working fine for you.

Thank you!
